return {
	coraca = {
		acceleration = 0.065999999642372,
		brakerate = 1.875,
		buildcostenergy = 8824,
		buildcostmetal = 231,
		builddistance = 128,
		builder = true,
		buildpic = "CORACA.DDS",
		buildtime = 18001,
		canfly = true,
		canmove = true,
		category = "ALL NOTLAND MOBILE ANTIGATOR NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOWEAPON NOTSHIP",
		collide = false,
		cruisealt = 70,
		description = "Tech Level 2",
		energymake = 10,
		energystorage = 50,
		energyuse = 10,
		explodeas = "CA_EX",
		footprintx = 2,
		footprintz = 2,
		icontype = "air",
		idleautoheal = 1.8500000238419,
		idletime = 900,
		maxdamage = 185,
		maxslope = 10,
		maxvelocity = 8.0500001907349,
		maxwaterdepth = 0,
		metalmake = 0.10000000149012,
		metalstorage = 50,
		name = "Advanced Construction Aircraft",
		objectname = "CORACA",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 383.5,
		terraformspeed = 650,
		turnrate = 121,
		workertime = 130,
		buildoptions = {
			[1] = "corgen",
			[2] = "corfus",
			[3] = "corplat",
			[4] = "cmgeo",
			[5] = "corbhmth",
			[6] = "cormoho",
			[7] = "cormexp",
			[8] = "cormmkr",
			[9] = "coruwadves",
			[10] = "coruwadvms",
			[11] = "corarad",
			[12] = "corshroud",
			[13] = "corfort",
			[14] = "corasp",
			[15] = "cortarg",
			[16] = "corsd",
			[17] = "corgate",
			[18] = "cortoast",
			[19] = "corvipe",
			[20] = "cordoom",
			[21] = "corflak",
			[22] = "screamer",
			[23] = "cortron",
			[24] = "corfmd",
			[25] = "corsilo",
			[26] = "corint",
			[27] = "corbuzz",
			[28] = "corap",
			[29] = "coraap",
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
	},
}
