return {
	armbandit = {
		acceleration = 0.1000001430511,
		brakerate = 0.1430000000298023,
		buildcostenergy = 1750,
		buildcostmetal = 210,
		buildpic = "ARMPW.DDS",
		buildtime = 1600,
		canmove = true,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "29 29 29",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		category = "KBOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR",
		corpse = "DEAD",
		description = "Medium Infantry Kbot",
		energymake = 0.30000001192093,
		energyuse = 0.30000001192093,
		explodeas = "SMALL_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 3,
		idletime = 900,
		maxdamage = 1250,
		maxslope = 17,
		maxvelocity = 1.45,
		maxwaterdepth = 12,
		movementclass = "KBOT2",
		name = "Bandit",
		nochasecategory = "VTOL",
		objectname = "armbandit",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 320,
		smoothanim = true,
		turnrate = 1056,
		upright = true,
		sfxtypes = {
		explosiongenerators = {
		"custom:flashmuzzle0",
		"custom:flashmuzzle1",
		},
	},
		featuredefs = {
			dead = {
				blocking = false,
				collisionvolumetype = "Box",
				collisionvolumescales = "30.1392364502 18.4953460693 29.797164917",
				collisionvolumeoffsets = "0.979118347168 -0.453806965332 -0.796119689941",
				category = "corpses",
				damage = 192,
				description = "Bandit Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 40,
				hitdensity = 100,
				metal = 102,
				object = "ARMPW_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 96,
				description = "Bandit Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 61,
				object = "2X2F",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servtny2",
			},
			select = {
				[1] = "servtny2",
			},
		},
		weapondefs = {
			gray_mgun = {
				accuracy = 200,
				areaofeffect = 8,
				beamtime = 0.10,
				corethickness = 0.40,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:EMG_HIT",
				edgeeffectiveness = 1,
				firestarter = 30,
				impactonly = 1,
				impulseboost = 0.1,
				impulsefactor = 0.1,
				color = 255,
				color2 = 226,
				name = "Machinegun",
				noselfdamage = true,
				projectiles = 1,
				range = 300,
				rendertype = 4,
				reloadtime = 0.7,
				soundhit = "xplosml3",
				soundstart = "RUS_45mm.wav",
				soundtrigger = true,
				sprayangle = 1000,
				targetmoveerror = 0.20000000298023,
				thickness = 1.20,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1400,
				damage = {
					bombers = 40,
					default = 65,
					fighters = 40,
					subs = 6,
					vtol = 40,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "gray_mgun",
			},
		},
	},
}
