return {
	armcsa = {
		acceleration = 0.083999998867512,
		brakerate = 1.875,
		buildcostenergy = 7000,
		buildcostmetal = 150,
		builddistance = 128,
		builder = true,
		buildpic = "ARMCSA.DDS",
		buildtime = 14098,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		category = "ALL NOTLAND MOBILE NOTSUB ANTIFLAME ANTIGATOR ANTIEMG ANTILASER VTOL NOWEAPON NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "26 15 26",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 70,
		description = "Tech Level 2",
		energymake = 10,
		energystorage = 75,
		explodeas = "CA_EX",
		floater = true,
		footprintx = 2,
		footprintz = 2,
		icontype = "air",
		idleautoheal = 1.3500000238419,
		idletime = 900,
		maxdamage = 135,
		maxslope = 10,
		maxvelocity = 8.9700002670288,
		maxwaterdepth = 255,
		metalmake = 0.1,
		metalstorage = 75,
		name = "Construction Seaplane",
		objectname = "ARMCSA",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 364,
		terraformspeed = 300,
		turnrate = 148,
		workertime = 60,
		buildoptions = {
			[1] = "armtide",
			[2] = "armuwmex",
			[3] = "armfmkr",
			[4] = "armmstor",
			[5] = "armestor",
			[6] = "armap",
			[7] = "armaap",
			[8] = "armplat",
			[9] = "armsy",
			[10] = "armhp",
			[11] = "asubpen",
			[12] = "armsonar",
			[13] = "armfrad",
			[14] = "armfdrag",
			[15] = "armdl",
			[16] = "armfrt",
			[17] = "armfhlt",
			[18] = "armtl",

		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel1",
			},
		},
	},
}
