return {
	armcrus = {
		acceleration = 0.048,
		activatewhenbuilt = true,
		brakerate = 0.062,
		buildangle = 16384,
		buildcostenergy = 17800,
		buildcostmetal = 2500,
		buildpic = "ARMCRUS.png",
		buildtime = 26000,
		canmove = true,
		category = "ALL NOTLAND MOBILE WEAPON NOTSUB SHIP NOTAIR",
		collisionvolumeoffsets = "0 -15 -1",
		collisionvolumescales = "39 39 195",
		collisionvolumetest = 1,
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		description = "Cruiser",
		explodeas = "BIG_UNITEX",
		floater = true,
		footprintx = 9,
		footprintz = 9,
		icontype = "sea",
		idleautoheal = 45.060001373291,
		idletime = 900,
		maxdamage = 5985,
		maxvelocity = 1.8,
		minwaterdepth = 30,
		movementclass = "BOAT5",
		name = "Conqueror",
		nochasecategory = "VTOL",
		objectname = "ARMCRUS",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		radardistance = 950,
		sightdistance = 500,
		sonardistance = 400,
		turnrate = 240,
		waterline = 5,
		sfxtypes = {
		explosiongenerators = {
		"custom:flashmuzzle1",
		"custom:RAIDMUZZLE",
		"custom:STORMMUZZLE",
		},
	},
		featuredefs = {
			dead = {
				blocking = false,
				collisionvolumetype = "Box",
				collisionvolumescales = "48.6282958984 40.4258880615 106.154632568",
				collisionvolumeoffsets = "-3.49415588379 -0.469155969238 -2.86915588379",
				category = "corpses",
				damage = 2704,
				description = "Conqueror Wreckage",
				energy = 0,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 4,
				hitdensity = 100,
				metal = 1272,
				object = "ARMCRUS_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 2016,
				description = "Conqueror Heap",
				energy = 0,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 466,
				object = "2X2A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sharmmov",
			},
			select = {
				[1] = "sharmsel",
			},
		},
		weapondefs = {
			arm_crus = {
				accuracy = 800,
				areaofeffect = 12,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:BIGGAUSS_Expl",
				gravityaffected = "true",
				impulseboost = 0.15,
				impulsefactor = 0.15,
				model = "gauss_round",
				name = "GaussCannon",
				noselfdamage = true,
				range = 750,
				reloadtime = 2.6,
				soundhit = "xplomed2",
				soundstart = "cannhvy1",
				sprayangle = 200,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 550,
				damage = {
					bombers = 41,
					default = 270,
					fighters = 41,
					subs = 5,
					vtol = 41,
				},
			},
			torpedo1 = {
				areaofeffect = 16,
				avoidfriendly = true,
				burst = 1,
				burstrate = 0.5,
				burnblow = true,
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH2",
				flighttime = 5,
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				model = "torpedo",
				name = "Torpedo",
				noselfdamage = true,
				propeller = true,
				range = 350,
				reloadtime = 4.8,
				soundhit = "xplodep1",
				soundstart = "torpedo1",
				tolerance = 32767,
				turnrate = 14000,
				turret = true,
				waterweapon = true,
				guidance = true,
				tracks = true,
				selfprop = true,
				startvelocity = 120,
				weaponacceleration = 120,
				weapontimer = 4,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 120,
				damage = {
					ships = 110,
					default = 200,
					subs = 110,
				},
			},
			lightflak1 = {
				accuracy = 800,
				areaofeffect = 80,
				burnblow = true,
				canattackground = false,
				color = 1,
				craterboost = 0,
				cratermult = 0,
				cylindertargetting = 1,
				edgeeffectiveness = 0.75,
				explosiongenerator = "custom:FLASH3",
				gravityaffected = "true",
				impulseboost = 0,
				impulsefactor = 0,
				name = "FlakCannon",
				noselfdamage = true,
				range = 650,
				reloadtime = 0.7,
				soundhit = "flakhit",
				soundstart = "flakfire",
				toairweapon = true,
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 1450,
				damage = {
					bombers = 50,
					commanders = 5,
					crawlingbombs = 5,
					default = 60,
					["else"] = 5,
					fighters = 60,
					heavyunits = 5,
					mines = 5,
					nanos = 5,
					subs = 5,
					vtol = 60,
				},
			},
		},
		weapons = {
			[1] = {
				def = "arm_crus",
				onlytargetcategory = "NOTAIR",
				MainDir = "0 0 1",
				MaxAngleDif = 270,
			},
			[2] = {
				def = "arm_crus",
				onlytargetcategory = "NOTAIR",
				MainDir = "0 0 1",
				MaxAngleDif = 270,
			},
			[3] = {
				def = "arm_crus",
				onlytargetcategory = "NOTAIR",
				MainDir = "0 0 -1",
				MaxAngleDif = 270,
			},
			[4] = {
				def = "arm_crus",
				onlytargetcategory = "NOTAIR",
				MainDir = "0 0 -1",
				MaxAngleDif = 270,
			},
			[5] = {
				def = "torpedo1",
				badtargetcategory = "HOVER NOTSHIP",
				onlytargetcategory = "SHIP UNDERWATER",
			},
			[6] = {
				def = "lightflak1",
			},
		},
	},
}
