return {
	armca = {
		acceleration = 0.071999996900558,
		brakerate = 1.875,
		buildcostenergy = 4320,
		buildcostmetal = 105,
		builddistance = 128,
		builder = true,
		buildpic = "ARMCA.png",
		buildtime = 8844,
		canfly = true,
		canmove = true,
		category = "ALL MOBILE NOTLAND NOTSUB ANTIFLAME ANTIGATOR ANTIEMG ANTILASER VTOL NOWEAPON NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "26 15 26",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 70,
		description = "Basic Builder",
		energymake = 5,
		energystorage = 25,
		explodeas = "CA_EX",
		footprintx = 2,
		footprintz = 2,
		icontype = "air",
		idleautoheal = 1.3999999761581,
		idletime = 900,
		maxdamage = 140,
		maxslope = 10,
		maxvelocity = 7.9400000572205,
		maxwaterdepth = 0,
		metalmake = 0.050000000745058,
		metalstorage = 25,
		name = "Construction Aircraft",
		objectname = "ARMCA",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 390,
		terraformspeed = 225,
		turnrate = 110,
		workertime = 55,
		buildoptions = {
			[1] = "armsolar",
			[2] = "armadvsol",
			[3] = "armwin",
			[4] = "armgeo",
			[5] = "armmstor",
			[6] = "armestor",
			[7] = "armmex",
			[8] = "armasp",
			[9] = "armaap",
			[10] = "armlab",
			[11] = "armvp",
			[12] = "armap",
			[13] = "armsy",
			[14] = "armhp",
			[15] = "armeyes",
			[16] = "armrad",
			[17] = "armdrag",
			[18] = "armclaw",
			[29] = "armllt",
			[20] = "tawf001",
			[21] = "armhlt",
			[22] = "armguard",
			[23] = "armrl",
			[24] = "packo",
			[25] = "armcir",
			[26] = "armdl",
			[27] = "armjamt",
			[28] = "ajuno",
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
	},
}
