return {
	armdido = {
		acceleration = 0.12,
		brakerate = 0.375,
		buildcostenergy = 2000,
		buildcostmetal = 160,
		buildpic = "ARMDIDO.png",
		buildtime = 3000,
		canmove = true,
		category = "KBOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR",
		corpse = "DEAD",
		description = "Light Flak Kbot (Anti Fighter)",
		explodeas = "BIG_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 8,
		idletime = 900,
		maxdamage = 700,
		maxslope = 14,
		maxvelocity = 1.8,
		maxwaterdepth = 12,
		movementclass = "KBOT2",
		name = "Dido",
		nochasecategory = "VTOL",
		objectname = "ARMDIDO",
		onoffable = false,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 580,
		smoothanim = true,
		turnrate = 990,
		sfxtypes = {
		explosiongenerators = {
		"custom:flashmuzzle1",
		"custom:flashmuzzle0",
		},
	},		
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "32.719619751 19.6731262207 35.1108398438",
				collisionvolumeoffsets = "-2.33637237549 -5.01163688965 -4.31414794922",
				category = "corpses",
				damage = 690,
				description = "Dido Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 102,
				object = "ARMDIDO_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 345,
				description = "Dido Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 61,
				object = "2X2A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			lightmobileflak = {
				accuracy = 700,
				areaofeffect = 120,
				burnblow = true,
				canattackground = false,
				color = 1,
				craterboost = 0,
				cratermult = 0,
				cylindertargetting = 1,
				edgeeffectiveness = 0.75,
				explosiongenerator = "custom:FLASH3",
				gravityaffected = "true",
				impulseboost = 0,
				impulsefactor = 0,
				name = "FlakCannon",
				noselfdamage = true,
				range = 650,
				reloadtime = 0.75,
				soundhit = "flakhit",
				soundstart = "flakfire",
				toairweapon = true,
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 1450,
				damage = {
					bombers = 23,
					commanders = 5,
					crawlingbombs = 5,
					default = 30,
					["else"] = 5,
					fighters = 30,
					heavyunits = 5,
					mines = 5,
					nanos = 5,
					subs = 5,
					vtol = 30,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "NOTAIR",
				def = "lightmobileflak",
			},
		},
	},
}
