return {
	armdreadx = {
		acceleration = 0.043000001460314,
		brakerate = 0.061999998986721,
		buildangle = 5384,
		buildcostenergy = 7000,
		buildcostmetal = 500,
		buildpic = "ARMDREADX.png",
		buildtime = 11000,
		canhover = true,
		canmove = true,
		category = "ALL MOBILE WEAPON NOTSUB NOTSHIP NOTAIR",
		collisionvolumeoffsets = "0 -7 -1",
		collisionvolumescales = "25 25 25",
		collisionvolumetest = 1,
		collisionvolumetype = "Box",
		corpse = "DEAD",
		description = "Light Weapon Platform",
		explodeas = "BIG_UNIT",
		footprintx = 4,
		footprintz = 4,
		icontype = "armthovr",
		idleautoheal = 35,
		idletime = 900,
		isfireplatform = 1,
		maxdamage = 3500,
		maxvelocity = 1.6,
		maxslope = 17,
		maxwaterdepth = 0,
		movementclass = "HOVER4",
		name = "Tortoise",
		nochasecategory = "ALL",
		objectname = "ARMDREADX",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 540,
		transportcapacity = 6,
		transportsize = 2,
		turnrate = 395,
		unloadspread = 5,
		sfxtypes = {
		explosiongenerators = {
		"custom:HOVERS_ON_GROUND",
		},
	},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "64.6317596436 60.2001953125 88.311706543",
				collisionvolumeoffsets = "3.81589508057 -2.34375000119e-06 -4.35322570801",
				category = "corpses",
				damage = 3096,
				description = "Dreadnaught Wreckage",
				energy = 0,
				footprintx = 4,
				footprintz = 4,
				height = 30,
				hitdensity = 100,
				metal = 346,
				object = "ArmdreadX_dead",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				collisionvolumetype = "Box",
				collisionvolumescales = "64.6317596436 60.2001953125 88.311706543",
				collisionvolumeoffsets = "3.81589508057 -2.34375000119e-06 -4.35322570801",
				category = "corpses",
				damage = 3096,
				description = "Dreadnaught Wreckage",
				energy = 0,
				footprintx = 4,
				footprintz = 4,
				height = 20,
				hitdensity = 100,
				metal = 121,
				object = "3X3F",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovlgok1",
			},
			select = {
				[1] = "hovlgsl1",
			},
		},
		weapondefs = {
			repulsor = {
				isshield = true,
				name = "PlasmaRepulsor",
				range = 35,
				shieldalpha = 0.40000000596046,
				shieldbadcolor = "0 0.0 1",
				shieldenergyuse = 1,
				shieldforce = 7,
				shieldgoodcolor = "0 0.0 1",
				shieldintercepttype = 1,
				shieldmaxspeed = 3500,
				shieldpower = 20,
				shieldpowerregen = 10,
				shieldpowerregenenergy = 1,
				shieldradius = 35,
				shieldrepulser = false,
				smartshield = true,
				visibleshield = true,
				visibleshieldhitframes = 70,
				visibleshieldrepulse = true,
				weapontype = "Shield",
				damage = {
					default = 100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "repulsor",
			},
		},
	},
}
