return {
	armfido = {
		acceleration = 0.11999999731779,
		brakerate = 0.375,
		buildcostenergy = 3450,
		buildcostmetal = 400,
		buildpic = "ARMFIDO.DDS",
		buildtime = 6924,
		canmove = true,
		category = "KBOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR",
		corpse = "DEAD",
		description = "Skirmish Gauss Kbot",
		energymake = 0.80000001192093,
		energyuse = 0.80000001192093,
		explodeas = "BIG_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 11.5,
		idletime = 900,
		maxdamage = 1000,
		maxslope = 14,
		maxvelocity = 1.7,
		maxwaterdepth = 12,
		movementclass = "KBOT2",
		name = "Fido",
		nochasecategory = "VTOL",
		objectname = "ARMFIDO",
		onoffable = false,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 580,
		smoothanim = true,
		turnrate = 990,
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "32.719619751 19.6731262207 35.1108398438",
				collisionvolumeoffsets = "-2.33637237549 -5.01163688965 -4.31414794922",
				category = "corpses",
				damage = 690,
				description = "Fido Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 302,
				object = "ARMFIDO_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 345,
				description = "Fido Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 121,
				object = "2X2A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			gauss = {
				areaofeffect = 8,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH1nd",
				impulseboost = 0.32300000339746,
				impulsefactor = 0.32300000339746,
				name = "GaussCannon",
				noselfdamage = true,
				range = 700,
				reloadtime = 1.9,
				soundhit = "xplomed2",
				soundstart = "cannhvy1",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 600,
				damage = {
					bombers = 35,
					default = 120,
					fighters = 35,
					subs = 5,
					vtol = 35,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "GAUSS",
			},
			[2] = {
				def = "BFIDO",
			},
		},
	},
}
