return {
	armfav = {
		acceleration = 0.11999999731779,
		brakerate = 0.16500000655651,
		buildcostenergy = 300,
		buildcostmetal = 30,
		buildpic = "ARMFAV.DDS",
		buildtime = 912,
		canmove = true,
		category = "ALL TANK MOBILE WEAPON NOTSUB NOTSHIP NOTAIR",
		corpse = "DEAD",
		description = "Light Scout Vehicle",
		energymake = 0.20000000298023,
		energyuse = 0.20000000298023,
		explodeas = "SMALL_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 0.80000001192093,
		idletime = 900,
		leavetracks = true,
		maxdamage = 80,
		maxslope = 26,
		maxvelocity = 6.4000000953674,
		maxwaterdepth = 12,
		movementclass = "TANK2",
		name = "Jeffy",
		nochasecategory = "VTOL",
		objectname = "ARMFAV",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 585,
		trackoffset = -3,
		trackstrength = 3,
		tracktype = "StdTank",
		trackwidth = 25,
		turnrate = 1144,
		featuredefs = {
			dead = {
				blocking = false,
				collisionvolumetype = "Box",
				collisionvolumescales = "26.3068695068 15.9473724365 28.9309844971",
				collisionvolumeoffsets = "0.351249694824 -0.179103781738 -0.672737121582",
				category = "corpses",
				damage = 111,
				description = "Jeffy Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 15,
				object = "ARMFAV_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 56,
				description = "Jeffy Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 6,
				object = "2X2F",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "varmmove",
			},
			select = {
				[1] = "varmsel",
			},
		},
		weapondefs = {
			gray_mgun = {
				areaofeffect = 8,
				burst = 6,
				burstrate = 0.15,
				beamtime = 0.10,
				corethickness = 0.15,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:EMG_HIT",
				edgeeffectiveness = 1,
				firestarter = 30,
				impactonly = 1,
				impulseboost = 0.1,
				impulsefactor = 0.1,
				color = 255,
				color2 = 226,
				name = "Machinegun",
				noselfdamage = true,
				projectiles = 1,
				range = 180,
				rendertype = 4,
				reloadtime = 2,
				soundhit = "softblat",
				soundstart = "softblam3",
				soundtrigger = true,
				sprayangle = 2312,
				targetmoveerror = 0.20000000298023,
				thickness = 0.5,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 700,
				damage = {
					bombers = 6,
					default = 10,
					fighters = 6,
					subs = 6,
					vtol = 3,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "gray_mgun",
			},
		},
	},
}
