return {
	armlift = {
		acceleration = 0.06,
		brakerate = 5.5,
		buildcostenergy = 7000,
		buildcostmetal = 480,
		buildpic = "ARMlift.png",
		buildtime = 9000,
		canfly = true,
		canmove = true,
		category = "ALL MOBILE WEAPON NOTLAND ANTIGATOR NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 -11 0",
		collisionvolumescales = "40 30 140",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 70,
		description = "Ship Transport",
		explodeas = "BIG_UNITEX",
		footprintx = 6,
		footprintz = 6,
		icontype = "air",
		idleautoheal = 20,
		idletime = 900,
		maxdamage = 1850,
		maxslope = 10,
		maxvelocity = 3.05,
		maxwaterdepth = 0,
		name = "Zeplin",
		objectname = "ARMlift",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 225,
		transportcapacity = 1,
        transportmass = 5000,
		transportsize = 12,
		turnrate = 200,
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
	},
}
