return {
	armmart = {
		acceleration = 0.018,
		brakerate = 0.123,
		buildcostenergy = 5800,
		buildcostmetal = 410,
		buildpic = "ARMMART.png",
		buildtime = 8500,
		canmove = true,
		category = "ALL TANK MOBILE WEAPON NOTSUB NOTSHIP NOTAIR",
		collisionvolumeoffsets = "0 -8 0",
		collisionvolumescales = "36 36 42",
		collisionvolumetest = 1,
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		description = "Mobile Artillery",
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 6,
		idletime = 900,
		leavetracks = true,
		maxdamage = 1020,
		maxslope = 12,
		maxvelocity = 1.8,
		maxwaterdepth = 0,
		movementclass = "TANK3",
		name = "Luger",
		nochasecategory = "NOTLAND VTOL",
		objectname = "ARMMART",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 286,
		trackoffset = -8,
		trackstrength = 8,
		tracktype = "StdTank",
		trackwidth = 35,
		turnrate = 402,
		sfxtypes = {
		explosiongenerators = {
		"custom:RAIDMUZZLE",
		"custom:STORMMUZZLE",
		},
	},
		customparams = {
			canareaattack = 1,
		},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "50.2839050293 32.1819000244 44.5333404541",
				collisionvolumeoffsets = "5.28918457031 -0.420549987793 0.245765686035",
				category = "corpses",
				damage = 360,
				description = "Luger Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 198,
				object = "ARMMART_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 180,
				description = "Luger Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 79,
				object = "2X2E",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
		weapondefs = {
			arm_artillery = {
				accuracy = 900,
				areaofeffect = 140,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:FLASH4",
				gravityaffected = "true",
				impulseboost = 0.15,
				impulsefactor = 0.15,
				name = "PlasmaCannon",
				noselfdamage = true,
				range = 800,
				reloadtime = 2.65,
				soundhit = "xplomed4",
				soundstart = "cannhvy2",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 355.28158569336,
				damage = {
					bombers = 15,
					default = 205,
					fighters = 15,
					subs = 5,
					vtol = 15,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ARM_ARTILLERY",
				maindir = "0 0 1",
				maxangledif = 180,
				onlytargetcategory = "NOTAIR",
			},
		},
	},
}
