return {
	armpnix = {
		acceleration = 0.072,
		brakerate = 5,
		buildcostenergy = 10500,
		buildcostmetal = 250,
		buildpic = "ARMPNIX.DDS",
		buildtime = 14000,
		canfly = true,
		canmove = true,
		category = "ALL NOTLAND MOBILE WEAPON ANTIGATOR NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "29 15 29",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 110,
		description = "Strategic Bomber",
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		icontype = "air",
		idleautoheal = 10,
		idletime = 900,
		maxdamage = 1050,
		maxslope = 10,
		maxvelocity = 9.37,
		maxwaterdepth = 0,
		name = "Phoenix",
		noautofire = true,
		nochasecategory = "VTOL",
		objectname = "ARMPNIX",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 260,
		turnrate = 402,
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
		weapondefs = {
			armadvbomb = {
				areaofeffect = 144,
				burst = 5,
				burstrate = 0.050000000745058,
				collidefriendly = false,
				commandfire = false,
				craterboost = 0,
				cratermult = 0,
				dropped = true,
				edgeeffectiveness = 0,
				explosiongenerator = "custom:ARM_BIGBOMB_EXPLOSION",
				gravityaffected = "true",
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				manualbombsettings = true,
				model = "bomb",
				name = "AdvancedBombs",
				noselfdamage = true,
				range = 1280,
				reloadtime = 9,
				soundhit = "xplomed2",
				soundstart = "bombrel",
				weapontype = "AircraftBomb",
				damage = {
					bombers = 5,
					default = 170,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "ARMADVBOMB",
			},
		},
	},
}
