return {
	armsy = {
		acceleration = 0,
		brakerate = 0,
		buildcostenergy = 2450,
		buildcostmetal = 800,
		builder = true,
		buildpic = "ARMSY.png",
		buildtime = 9000,
		CanBeAssisted = false,
		canmove = true,
		category = "ALL PLANT NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR UNDERWATER",
		collisionvolumeoffsets = "0 -40 0",
		collisionvolumescales = "186 90 226",
		collisionvolumetest = 1,
		collisionvolumetype = "Box",
		corpse = "DEAD",
		description = "Produces Basic Ships",
		energystorage = 100,
		explodeas = "LARGE_BUILDINGEX",
		footprintx = 12,
		footprintz = 18,
		icontype = "building",
		idleautoheal = 29.89999961853,
		idletime = 900,
		maxdamage = 4500,
		metalmake = 0.5,
		metalstorage = 100,
		minwaterdepth = 30,
		name = "Shipyard",
		objectname = "ARMSY",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "LARGE_BUILDING",
		sightdistance = 275.60000610352,
		terraformspeed = 500,
		waterline = 1,
		workertime = 400,
		yardmap = "CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC CCCCCCCCCCCC",
		buildoptions = {
			[1] = "armcs",
			[2] = "armlightfrigate",
			[3] = "armdest",
			[4] = "armcrus",
			[5] = "armsub",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "-2 -2 -3",
				collisionvolumescales = "116 52 116",
				collisionvolumetest = 1,
				collisionvolumetype = "Box",
				damage = 1794,
				description = "Shipyard Wreckage",
				energy = 0,
				footprintx = 7,
				footprintz = 7,
				height = 4,
				hitdensity = 100,
				metal = 400,
				object = "ARMSY_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:YellowLight",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "untdone",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "pshpactv",
			},
		},
	},
}
