return {
	armsbot = {
		acceleration = 0.26000001430511,
		brakerate = 0.15000000298023,
		buildcostenergy = 1300,
		buildcostmetal = 150,
		buildpic = "Armsbot.pcx",
		buildtime = 2200,
		canmove = true,
		category = "KBOT MOBILE WEAPON ALL NOTSUB NOTSHIP NOTAIR",
		corpse = "DEAD",
		cloakcost = 6,
		cloakcostmoving = 12,
		mincloakdistance = 75,
		description = "Light Cloak Kbot",
		explodeas = "SMALL_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 3,
		idletime = 900,
		maxdamage = 650,
		maxslope = 17,
		maxvelocity = 2.3,
		maxwaterdepth = 12,
		movementclass = "KBOT2",
		name = "Shimmer",
		nochasecategory = "VTOL",
		objectname = "armsbot",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 320,
		smoothanim = true,
		turnrate = 1056,
		upright = true,
		sfxtypes = {
		explosiongenerators = {
		"custom:flashmuzzle0",
		"custom:flashmuzzle1",
		},
	},
		featuredefs = {
			dead = {
				blocking = false,
				category = "heaps",
				damage = 96,
				description = "Shimmer Wreak",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 97,
				object = "2X2F",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 96,
				description = "Shimmer Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 48,
				object = "2X2F",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "servtny2",
			},
			select = {
				[1] = "servtny2",
			},
		},
		weapondefs = {
			arm_lightcannon = {
				areaofeffect = 24,
				avoidfeature = false,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:LIGHT_PLASMA",
				firestarter = 100,
				gravityaffected = "true",
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				name = "LightCannon",
				noselfdamage = true,
				range = 200,
				reloadtime = 1.4,
				soundhit = "xplomed3",
				soundstart = "cannon1",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 350,
				damage = {
					bombers = 18,
					default = 56,
					fighters = 18,
					subs = 5,
					vtol = 18,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "arm_lightcannon",
			},
		},
	},
}
