return {
	armsaber = {
		acceleration = 0.288,
		brakerate = 4.613,
		buildcostenergy = 4200,
		buildcostmetal = 270,
		buildpic = "ARMSABER.DDS",
		buildtime = 9000,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		category = "ALL NOTLAND MOBILE WEAPON ANTIGATOR NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 -6 0",
		collisionvolumescales = "33 25 33",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 100,
		description = "Seaplane Gunship",
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 6.4,
		idletime = 900,
		maxdamage = 840,
		maxslope = 10,
		maxvelocity = 5.23,
		maxwaterdepth = 255,
		name = "Sabre",
		nochasecategory = "VTOL",
		objectname = "ARMSABER",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 595,
		turnrate = 931,
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel1",
			},
		},
		weapondefs = {
			vtol_emg2 = {
				areaofeffect = 8,
				beamtime = 0.10000000149012,
				corethickness = 0.20000000298023,
				craterboost = 0,
				cratermult = 0,
				energypershot = 35,
				explosiongenerator = "custom:SMALL_GREEN_LASER_BURN",
				firestarter = 90,
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				name = "HighEnergyLaser",
				noselfdamage = true,
				range = 420,
				reloadtime = 1.,
				rgbcolor = "0 1 0",
				soundhit = "lasrhit1",
				soundstart = "Lasrmas2",
				targetmoveerror = 0.30000001192093,
				thickness = 2.9000000953674,
				turret = false,
				weapontype = "LaserCannon",
				weaponvelocity = 800,
				damage = {
					bombers = 10,
					default = 115,
					fighters = 10,
					subs = 1,
					vtol = 10,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "VTOL_EMG2",
				onlytargetcategory = "NOTAIR",
			},
		},
	},
}
