return {
	armsub = {
		acceleration = 0.018,
		activatewhenbuilt = true,
		brakerate = 0.1,
		buildcostenergy = 6000,
		buildcostmetal = 750,
		buildpic = "ARMSUB.png",
		buildtime = 14000,
		canmove = true,
		category = "UNDERWATER ALL MOBILE WEAPON NOTLAND NOTAIR",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "38 20 60",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		corpse = "DEAD",
		description = "Submarine (Anti Captial Ship)",
		explodeas = "SMALL_UNITEX",
		footprintx = 5,
		footprintz = 5,
		icontype = "sea",
		idleautoheal = 8,
		idletime = 900,
		maxdamage = 1200,
		maxvelocity = 1.9,
		minwaterdepth = 20,
		movementclass = "UBOAT5",
		name = "Piranha",
		nochasecategory = "VTOL",
		objectname = "ARMSUB",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 364,
		sonardistance = 450,
		turnrate = 355,
		upright = true,
		waterline = 30,
		featuredefs = {
			dead = {
				blocking = false,
				collisionvolumetype = "Box",
				collisionvolumescales = "40.4452667236 15.0652923584 47.2016448975",
				collisionvolumeoffsets = "-1.03743743896 -3.82080078154e-06 -0.269828796387",
				category = "corpses",
				damage = 501,
				description = "Lurker Wreckage",
				energy = 0,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 423,
				object = "ARMSUB_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 2016,
				description = "Lurker Heap",
				energy = 0,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 251,
				object = "3X3A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "suarmmov",
			},
			select = {
				[1] = "suarmsel",
			},
		},
		weapondefs = {
			arm_torpedo = {
				areaofeffect = 16,
				avoidfriendly = true,
				burst = 3,
				burstrate = 0.5,
				burnblow = true,
				collidefriendly = false,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASH2",
				flighttime = 4,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "torpedo",
				name = "Torpedo",
				noselfdamage = true,
				propeller = true,
				range = 350,
				reloadtime = 6,
				soundhit = "xplodep1",
				soundstart = "torpedo1",
				tolerance = 32500,
				turnrate = 14000,
				turret = false,
				waterweapon = true,
				guidance = true,
				tracks = true,
				selfprop = true,
				startvelocity = 120,
				weaponacceleration = 120,
				weapontimer = 4,
				weapontype = "TorpedoLauncher",
				weaponvelocity = 120,
				damage = {
					ships = 200,
					default = 300,
					subs = 200,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "HOVER NOTSHIP",
				def = "ARM_TORPEDO",
				maindir = "0 0 1",
				maxangledif = 90,
				onlytargetcategory = "SHIP UNDERWATER",
			},
		},
	},
}
