return {
	armwar = {
		acceleration = 0.071999996900558,
		brakerate = 0.23800000548363,
		buildcostenergy = 2600,
		buildcostmetal = 260,
		buildpic = "ARMWAR.png",
		buildtime = 4000,
		canmove = true,
		category = "KBOT MOBILE WEAPON ALL ANTIGATOR NOTSUB ANTIEMG NOTSHIP NOTAIR",
		corpse = "DEAD",
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "27 32 27",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		description = "Heavy Shotgun Kbot",
		energymake = 0.5,
		energyuse = 0.5,
		explodeas = "SMALL_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 13,
		idletime = 900,
		maxdamage = 1800,
		maxslope = 17,
		maxvelocity = 1.1,
		maxwaterdepth = 12,
		movementclass = "KBOT2",
		name = "Warrior",
		nochasecategory = "VTOL",
		objectname = "ARMWAR",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 350,
		smoothanim = true,
		turnrate = 770,
		upright = true,
		sfxtypes = {
		explosiongenerators = {
		"custom:STOMPDUST",
		"custom:RAIDMUZZLE",
		"custom:flashmuzzle0",
		},
	},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "40 10 42",
				collisionvolumeoffsets = "-0.527076721191 -5.09926749023 6.06378173828",
				category = "corpses",
				damage = 780,
				description = "Warrior Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 141,
				object = "ARMWAR_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 390,
				description = "Warrior Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 64,
				object = "2X2A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			armwar_laser = {
				areaofeffect = 8,
				beamtime = 0.15,
				corethickness = 0.12,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:EMG_HIT",
				firestarter = 30,
				impactonly = 1,
				impulseboost = 12.5,
				impulsefactor = 12.5,
				laserflaresize = 5,
				name = "Shotgun",
				noselfdamage = true,
				projectiles = 12,
				range = 230,
				reloadtime = 1,
				rgbcolor = "0.5 0.5 0",
				soundhit = "xplosml3",
				soundstart = "canlite3",
				soundtrigger = true,
				sprayangle = 2500,
				targetmoveerror = 0.20000000298023,
				thickness = 1.6,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 500,
				damage = {
					bombers = 7,
					default = 24,
					fighters = 7,
					subs = 5,
					vtol = 7,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ARMWAR_LASER",
			},
		},
	},
}
