return {
	cafus = {
		acceleration = 0,
		brakerate = 0,
		buildangle = 4096,
		buildcostenergy = 35000,
		buildcostmetal = 12000,
		buildinggrounddecaldecayspeed = 30,
		buildinggrounddecalsizex = 9,
		buildinggrounddecalsizey = 9,
		buildinggrounddecaltype = "cafus_aoplane.dds",
		buildpic = "CAFUS.png",
		buildtime = 128390,
		category = "ALL NOTSUB NOWEAPON SPECIAL NOTAIR",
		corpse = "DEAD",
		collisionvolumeoffsets = "0 0 -2",
		collisionvolumescales = "60 57 60",
		collisionvolumetest = 1,
		collisionvolumetype = "Box",
		description = "Enhanced Energy Output",
		energymake = 4000,
		energystorage = 12000,
		explodeas = "NUCLEAR_MISSILE",
		footprintx = 6,
		footprintz = 6,
		icontype = "building",
		idleautoheal = 85,
		idletime = 900,
		maxdamage = 9000,
		maxslope = 13,
		maxwaterdepth = 0,
		name = "Advanced Fusion Reactor",
		objectname = "CAFUS",
		seismicsignature = 0,
		selfdestructas = "CRBLMSSL",
		sightdistance = 273,
		usebuildinggrounddecal = true,
		yardmap = "oooooooooooooooooooooooooooooooooooo",
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "114.264892578 89.6709289551 97.8311309814",
				collisionvolumeoffsets = "-5.1672668457 -0.194635522461 -0.799919128418",
				category = "corpses",
				damage = 17100,
				description = "Advanced Fusion Reactor Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 5,
				footprintz = 4,
				height = 20,
				hitdensity = 100,
				metal = 6040,
				object = "CAFUS_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 8550,
				description = "Advanced Fusion Reactor Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 5,
				footprintz = 4,
				height = 4,
				hitdensity = 100,
				metal = 2276,
				object = "4X4A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "fusion2",
			},
		},
	},
}
