return {
	corcut = {
		acceleration = 0.125,
		brakerate = 3.938,
		buildcostenergy = 3800,
		buildcostmetal = 340,
		buildpic = "CORCUT.png",
		buildtime = 9000,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		category = "ALL MOBILE WEAPON ANTIGATOR VTOL ANTIFLAME ANTIEMG ANTILASER NOTLAND NOTSUB NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 -9 0",
		collisionvolumescales = "33 25 33",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 100,
		description = "Seaplane Gunship",
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 8.5,
		idletime = 900,
		maxdamage = 920,
		maxslope = 10,
		maxvelocity = 5.0799999237061,
		maxwaterdepth = 255,
		name = "Cutlass",
		nochasecategory = "VTOL",
		objectname = "CORCUT",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 595,
		turnrate = 828,
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel2",
			},
		},
		weapondefs = {
			vtol_rocket2 = {
				areaofeffect = 128,
				burnblow = true,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:FLASHSMALLBUILDINGEX",
				impulseboost = 1.1,
				impulsefactor = 1.1,
				name = "RiotCannon",
				noselfdamage = true,
				range = 430,
				reloadtime = 1.6,
				soundhit = "xplosml3",
				soundstart = "canlite3",
				soundtrigger = true,
				turret = false,
				weapontype = "Cannon",
				weaponvelocity = 600,
				damage = {
					bombers = 17,
					default = 140,
					fighters = 17,
					subs = 5,
					vtol = 17,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "VTOL_ROCKET2",
				onlytargetcategory = "NOTAIR",
			},
		},
	},
}
