return {
	corcsa = {
		acceleration = 0.071999996900558,
		brakerate = 1.875,
		buildcostenergy = 7000,
		buildcostmetal = 150,
		builddistance = 128,
		builder = true,
		buildpic = "CORCSA.DDS",
		buildtime = 14904,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		category = "ALL NOTLAND MOBILE ANTIGATOR NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOWEAPON NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "26 15 26",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 75,
		description = "Tech Level 2",
		energymake = 10,
		energystorage = 75,
		explodeas = "CA_EX",
		footprintx = 2,
		footprintz = 2,
		icontype = "air",
		idleautoheal = 1.3999999761581,
		idletime = 900,
		maxdamage = 140,
		maxslope = 10,
		maxvelocity = 8.5100002288818,
		maxwaterdepth = 255,
		metalmake = 0.1,
		metalstorage = 75,
		name = "Construction Seaplane",
		objectname = "CORCSA",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 351,
		terraformspeed = 300,
		turnrate = 132,
		workertime = 60,
		buildoptions = {
			[1] = "cortide",
			[2] = "coruwmex",
			[3] = "corfmkr",
			[4] = "cormstor",
			[5] = "corestor",
			[6] = "corap",
			[7] = "coraap",
			[8] = "corplat",
			[9] = "corsy",
			[10] = "corhp",
			[11] = "csubpen",
			[12] = "corsonar",
			[13] = "corfrad",
			[14] = "corfdrag",
			[15] = "cordl",
			[16] = "corfrt",
			[17] = "corfhlt",
			[18] = "cortl",

		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel2",
			},
		},
	},
}
