return {
	cordecom = {
		acceleration = 0.18000000715256,
		activatewhenbuilt = true,
		autoheal = 5,
		brakerate = 0.375,
		buildcostenergy = 12000,
		buildcostmetal = 700,
		builddistance = 128,
		builder = true,
		buildpic = "CORDECOM.png",
		buildtime = 24000,
		candgun = true,
		canmove = true,
		category = "ALL WEAPON NOTSUB NOTSHIP NOTAIR UNDERWATER",
		cloakcost = 30,
		cloakcostmoving = 180,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "36 44 26",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		decoyfor = "corcom",
		description = "Decoy Commander",
		energymake = 15,
		energystorage = 100,
		explodeas = "DECOY_COMMANDER_BLAST",
		footprintx = 2,
		footprintz = 2,
		hidedamage = true,
		icontype = "corcommander",
		idleautoheal = 30,
		idletime = 900,
		mass = 5000,
		maxdamage = 3000,
		maxslope = 20,
		maxvelocity = 1.25,
		maxwaterdepth = 35,
		metalmake = 0.5,
		metalstorage = 100,
		mincloakdistance = 50,
		movementclass = "AKBOT2",
		name = "Commander",
		nochasecategory = "VTOL",
		objectname = "CORCOM.S3O",
		radardistance = 50,
		reclaimable = false,
		seismicsignature = 0,
		selfdestructas = "DECOY_COMMANDER_BLAST",
		showplayername = true,
		sightdistance = 377,
		smoothanim = true,
		terraformspeed = 750,
		transportbyenemy = false,
		turnrate = 1133,
		upright = true,
		workertime = 150,
		buildoptions = {
			[1] = "corsolar",
			[2] = "cortide",
			[3] = "corwin",
			[4] = "cormstor",
			[5] = "corestor",
			[6] = "cormex",
		},
		customparams = {
			paralyzemultiplier = 0.025000000372529,
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			armcomlaser = {
				areaofeffect = 12,
				avoidfeature = false,
				beamtime = 0.10000000149012,
				corethickness = 0.10000000149012,
				craterboost = 0,
				cratermult = 0,
				cylindertargetting = 1,
				duration = 0.1,				
				edgeeffectiveness = 0.99000000953674,
				explosiongenerator = "custom:SMALL_RED_BURN",
				firestarter = 70,
				impactonly = 1,
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				laserflaresize = 7,
				name = "J7Laser",
				noselfdamage = true,
				range = 300,
				reloadtime = 0.60000000596046,
				rgbcolor = "1 0 0",
				soundhit = "lasrhit2",
				soundstart = "lasrfir1",
				soundtrigger = true,
				targetmoveerror = 0.050000000745058,
				thickness = 3,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 900,
				damage = {
					bombers = 180,
					default = 105,
					fighters = 110,
					subs = 5,
				},
			},
			comblaster = {
				areaofeffect = 300,
				burnblow = true,
				cegTag = "MINIPLASMA",
				craterboost = 0,
				cratermult = 0,
				commandfire = true,
				edgeeffectiveness = 0.75,
				explosiongenerator = "custom:FLASH64",
				impulseboost = 0.38,
				impulsefactor = 0.38,
				name = "ComBlaster",
				noselfdamage = true,
				range = 300,
				reloadtime = 1.4,
				soundhit = "xplosml3",
				soundstart = "canlite3",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 550,
				damage = {
					default = 5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARMCOMLASER",
			},
			[3] = {
				def = "comblaster",
			},
		},
	},
}
