return {
	corfred = {
		acceleration = 0.082500003278255,
		brakerate = 0.13750000298023,
		buildcostenergy = 3500,
		buildcostmetal = 180,
		builddistance = 128,
		builder = true,
		buildpic = "corfred.png",
		buildtime = 6793,
		canmove = true,
		category = "ALL TANK MOBILE NOTSUB NOWEAPON NOTSHIP NOTAIR",
		corpse = "DEAD",
		description = "Fast Assist Vehicle",
		energymake = 15,
		energystorage = 100,
		energyuse = 15,
		explodeas = "BIG_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 9.75,
		idletime = 900,
		leavetracks = true,
		maxdamage = 600,
		maxslope = 18,
		maxvelocity = 2.7829999923706,
		maxwaterdepth = 18,
		metalmake = 0.15000000596046,
		metalstorage = 100,
		movementclass = "TANK2",
		name = "Fred",
		objectname = "corfred",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 500,
		terraformspeed = 750,
		trackoffset = 6,
		trackstrength = 5,
		tracktype = "StdTank",
		trackwidth = 31,
		turnrate = 635,
		workertime = 140,
		buildoptions = {
			[1] = "corsolar",
			[2] = "corwin",
			[3] = "cormex",
			[4] = "coreyes",
			[5] = "corrad",
			[6] = "corjamt",
		},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "31.1572570801 15.4860076904 32.9478607178",
				collisionvolumeoffsets = "5.1371307373 1.73223384521 4.24182891846",
				category = "corpses",
				damage = 585,
				description = "Fred Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 133,
				object = "CORFRED_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 293,
				description = "Fred Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 51,
				object = "3X3A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
	},
}
