return {
	corfav = {
		acceleration = 0.10999999940395,
		brakerate = 0.14499999582767,
		buildcostenergy = 300,
		buildcostmetal = 30,
		buildpic = "CORFAV.DDS",
		buildtime = 1104,
		canmove = true,
		category = "ALL TANK MOBILE WEAPON NOTSUB NOTSHIP NOTAIR",
		corpse = "DEAD",
		description = "Light Scout Vehicle",
		energymake = 0.30000001192093,
		energyuse = 0.30000001192093,
		explodeas = "SMALL_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 0.94999998807907,
		idletime = 900,
		leavetracks = true,
		maxdamage = 95,
		maxslope = 26,
		maxvelocity = 4.8899998664856,
		maxwaterdepth = 12,
		movementclass = "TANK2",
		name = "Weasel",
		nochasecategory = "VTOL",
		objectname = "CORFAV",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 535,
		trackoffset = -3,
		trackstrength = 3,
		tracktype = "StdTank",
		trackwidth = 27,
		turnrate = 1097,
		featuredefs = {
			dead = {
				blocking = false,
				collisionvolumetype = "Box",
				collisionvolumescales = "27.7855834961 9.28491210938 30.4499664307",
				collisionvolumeoffsets = "0.0 -2.81028394531 1.25487518311",
				category = "corpses",
				damage = 132,
				description = "Weasel Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 16,
				object = "CORFAV_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 66,
				description = "Weasel Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 6,
				object = "2X2B",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vcormove",
			},
			select = {
				[1] = "vcorsel",
			},
		},
		weapondefs = {
			gray_mgun = {
				areaofeffect = 8,
				burst = 6,
				burstrate = 0.15,
				beamtime = 0.10,
				corethickness = 0.15,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:EMG_HIT",
				edgeeffectiveness = 1,
				firestarter = 30,
				impactonly = 1,
				impulseboost = 0.1,
				impulsefactor = 0.1,
				color = 255,
				color2 = 226,
				name = "Machinegun",
				noselfdamage = true,
				projectiles = 1,
				range = 180,
				rendertype = 4,
				reloadtime = 2,
				soundhit = "softblat",
				soundstart = "softblam3",
				soundtrigger = true,
				sprayangle = 2312,
				targetmoveerror = 0.20000000298023,
				thickness = 0.5,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 700,
				damage = {
					bombers = 6,
					default = 10,
					fighters = 6,
					subs = 6,
					vtol = 3,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "gray_mgun",
			},
		},
	},
}
