return {
	corhurc = {
		acceleration = 0.06,
		brakerate = 0.625,
		buildcostenergy = 13500,
		buildcostmetal = 315,
		buildpic = "CORHURC.png",
		buildtime = 15000,
		canfly = true,
		canmove = true,
		category = "ALL NOTLAND MOBILE WEAPON ANTIGATOR VTOL ANTIFLAME ANTIEMG ANTILASER NOTSUB NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 -4 0",
		collisionvolumescales = "29 15 29",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 110,
		description = "Heavy Strategic Bomber",
		explodeas = "BIG_UNITEX",
		footprintx = 4,
		footprintz = 4,
		icontype = "air",
		idleautoheal = 13,
		idletime = 900,
		maxdamage = 1315,
		maxslope = 10,
		maxvelocity = 9,
		maxwaterdepth = 0,
		name = "Hurricane",
		noautofire = true,
		nochasecategory = "VTOL",
		objectname = "CORHURC",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 221,
		turnrate = 220,
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
		weapondefs = {
			coradvbomb = {
				areaofeffect = 180,
				burst = 5,
				burstrate = 0.050000000745058,
				collidefriendly = false,
				commandfire = false,
				craterboost = 0,
				cratermult = 0,
				dropped = true,
				edgeeffectiveness = 0,
				explosiongenerator = "custom:CORE_BIGBOMB_EXPLOSION",
				gravityaffected = "true",
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				manualbombsettings = true,
				model = "bomb",
				name = "AdvancedBombs",
				noselfdamage = true,
				range = 1280,
				reloadtime = 9,
				soundhit = "xplomed2",
				soundstart = "bombrel",
				weapontype = "AircraftBomb",
				damage = {
					bombers = 5,
					default = 230,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "CORADVBOMB",
			},
		},
	},
}
