return {
	corhunt = {
		acceleration = 0.06,
		brakerate = 3.75,
		buildcostenergy = 6600,
		buildcostmetal = 120,
		buildpic = "CORHUNT.png",
		buildtime = 9500,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		category = "ALL ANTIEMG NOTLAND MOBILE ANTIGATOR NOTSUB ANTIFLAME ANTILASER VTOL NOWEAPON NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "26 15 26",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 110,
		description = "Radar/Sonar Seaplane",
		energymake = 15,
		energyuse = 15,
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		icontype = "air",
		idleautoheal = 6.6,
		idletime = 900,
		maxdamage = 660,
		maxslope = 10,
		maxvelocity = 10.8,
		maxwaterdepth = 255,
		name = "Hunter",
		objectname = "CORHUNT",
		radardistance = 2200,
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 1130,
		sonardistance = 900,
		turnrate = 450,
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seasonr2",
			},
		},
	},
}
