return {
	corjar = {
		acceleration = 0.05,
		brakerate = 0.2,
		buildcostenergy = 2500,
		buildcostmetal = 255,
		buildpic = "CORJAR.pcx",
		buildtime = 3900,
		canmove = true,
		category = "KBOT MOBILE WEAPON ALL ANTIGATOR NOTSUB ANTIEMG NOTSHIP NOTAIR",
		corpse = "DEAD",
		customparams = {
      turretyawrate = 180,
	  turretpitchrate = 100,
	  dpslimit = 160,
    },	
		description = "Armoured Flame Kbot",
		energymake = 0,
		energyuse = 0,
		explodeas = "SMALL_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 13,
		idletime = 900,
		maxdamage = 2000,
		maxslope = 17,
		maxvelocity = 1,
		maxwaterdepth = 12,
		movementclass = "KBOT2",
		name = "The Jar",
		nochasecategory = "VTOL",
		objectname = "CORJAR",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 230,
		smoothanim = true,
		turnrate = 500,
		upright = true,
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:pyroflame",
				[2] = "custom:jarflamethrower"
			},
		},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "37.3442840576 10.0486450195 42.9995422363",
				collisionvolumeoffsets = "-0.527076721191 -5.09926749023 6.06378173828",
				category = "corpses",
				damage = 780,
				description = "Jar Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 181,
				object = "CORJAR_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 390,
				description = "Jar Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 83,
				object = "2X2A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			flamer = {
				accuracy = 800,
				groundbounce = true,
				areaOfEffect = 60,
				avoidFeature = false,
				coreThickness = 0,
				duration = 1,
				energypershot = 1,
				explosiongenerator = "custom:none",
				fallOffRate = 1,
				fireStarter = 50,
				soundstart = "Flamhvy1",
				model = "none",
				lineOfSight = true,
				minintensity = 0.1,
				noexplode = true,
				impulseFactor = 0,
				name = "Flamer",
				range = 220,
				reloadtime = 0.3,
				WeaponType = "LaserCannon",
				rgbColor = "0 0 0",
				rgbColor2 = "0 0 0",
				thickness = 0,
				tolerance = 1000,
				turret = true,
				weaponVelocity = 500,
				damage = {
					default = 30,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "flamer",
			},
		},
	},
}
