return {
	corlift = {
		acceleration = 0.06,
		brakerate = 5.5,
		buildcostenergy = 6000,
		buildcostmetal = 500,
		buildpic = "corlift.png",
		buildtime = 9000,
		canfly = true,
		canmove = true,
		category = "ALL MOBILE WEAPON NOTLAND ANTIGATOR VTOL ANTIFLAME ANTIEMG ANTILASER NOTSUB NOTSHIP",
		collide = false,
		collisionvolumeoffsets = "0 -4 0",
		collisionvolumescales = "35 30 150",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		cruisealt = 70,
		description = "Ship Transport",
		explodeas = "BIG_UNITEX",
		footprintx = 6,
		footprintz = 6,
		icontype = "air",
		idleautoheal = 12,
		idletime = 900,
		maxdamage = 2200,
		maxslope = 10,
		maxvelocity = 2.8,
		maxwaterdepth = 0,
		name = "Blimp",
		objectname = "corlift",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 225,
		transportcapacity = 1,
        transportmass = 5000,
		transportsize = 12,
		turnrate = 200,
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
	},
}
