return {
	cormak = {
		acceleration = 0.091999996900558,
		brakerate = 0.123,
		buildcostenergy = 2000,
		buildcostmetal = 205,
		buildpic = "CORMAK.DDS",
		buildtime = 2400,
		canmove = true,
		category = "KBOT MOBILE WEAPON ALL NOTSUB ANTIEMG NOTSHIP NOTAIR",
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "33 33 33",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		corpse = "DEAD",
		description = "Medium Infantry Kbot",
		energymake = 0.0,
		energyuse = 0.0,
		explodeas = "SMALL_UNITEX",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 13,
		idletime = 900,
		maxdamage = 1200,
		maxslope = 22,
		maxvelocity = 1.5,
		maxwaterdepth = 12,
		movementclass = "KBOT2",
		name = "Outlaw",
		nochasecategory = "VTOL",
		objectname = "CORMAK",
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 320,
		smoothanim = true,
		turnrate = 1050,
		upright = true,
		sfxtypes = {
		explosiongenerators = {
		"custom:RAIDMUZZLE",
		"custom:WOLVMUZZLE",
		"custom:THUDDUST",
		},
	},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "40 10 42",
				collisionvolumeoffsets = "-0.527076721191 -5.09926749023 6.06378173828",
				category = "corpses",
				damage = 780,
				description = "Outlaw Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 132,
				object = "cormak_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 390,
				description = "Outlaw Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 4,
				hitdensity = 100,
				metal = 65,
				object = "2X2A",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			outlaw_gun = {
				areaofeffect = 8,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:LIGHT_PLASMA",
				impactonly = 1,
				impulseboost = 0.1,
				impulsefactor = 0.1,
				name = "Outlaw Gun",
				noselfdamage = true,
				projectiles = 1,
				range = 300,
				rendertype = 4,
				reloadtime = 1.2,
				soundhit = "xplosml3",
				soundstart = "canlite3",
				soundtrigger = true,
				targetmoveerror = 0.20000000298023,
				tolerance = 1000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 350,
				damage = {
					bombers = 9,
					default = 80,
					fighters = 9,
					subs = 5,
					vtol = 9,
				},
			},
			gator_laser = {
				areaofeffect = 8,
				beamtime = 0.10000000149012,
				corethickness = 0.17499999701977,
				craterboost = 0,
				cratermult = 0,
				energypershot = 0,
				explosiongenerator = "custom:SMALL_RED_BURN",
				firestarter = 50,
				impactonly = 1,
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				laserflaresize = 6,
				name = "Laser",
				noselfdamage = true,
				range = 240,
				reloadtime = 0.5,
				rgbcolor = "1 0 0",
				soundhit = "lasrhit2",
				soundstart = "lasrlit3",
				soundtrigger = true,
				targetmoveerror = 0.15000000596046,
				thickness = 2.5,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 600,
				damage = {
					bombers = 4,
					default = 35,
					fighters = 4,
					subs = 1,
					vtol = 4,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "gator_laser",
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "outlaw_gun",
			},
		},
	},
}
