return {
	cormh = {
		acceleration = 0.071999996900558,
		brakerate = 0.11200000345707,
		buildcostenergy = 3200,
		buildcostmetal = 315,
		buildpic = "CORMH.png",
		buildtime = 4500,
		canhover = true,
		canmove = true,
		category = "ALL HOVER MOBILE WEAPON NOTSUB NOTSHIP NOTAIR",
		corpse = "DEAD",
		description = "Hovercraft Rocket Launcher",
		explodeas = "BIG_UNITEX",
		footprintx = 3,
		footprintz = 3,
		idleautoheal = 4.9499998092651,
		idletime = 900,
		maxdamage = 715,
		maxslope = 16,
		maxvelocity = 1.8,
		maxwaterdepth = 0,
		movementclass = "HOVER3",
		name = "Nixer",
		nochasecategory = "VTOL",
		objectname = "CORMH",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 500,
		turnrate = 355,
		featuredefs = {
			dead = {
				blocking = false,
				collisionvolumetype = "Box",
				collisionvolumescales = "30.0869903564 18.3419342041 34.3326873779",
				collisionvolumeoffsets = "-0.112327575684 -0.511842897949 -0.201560974121",
				category = "corpses",
				damage = 297,
				description = "Nixer Wreckage",
				energy = 0,
				featuredead = "HEAP",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 179,
				object = "CORMH_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 149,
				description = "Nixer Heap",
				energy = 0,
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 88,
				object = "3X3C",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "hovmdok2",
			},
			select = {
				[1] = "hovmdsl2",
			},
		},
		weapondefs = {
			cormh_weapon1 = {
				accuracy = 800, 
				areaofeffect = 60,
				cegTag = "raventrail",
				texture1 = "null",
				texture2 = "null",
				texture3 = "null",
				texture4 = "null",
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:SMALLFLASH_Expl",
				firestarter = 100,
				flighttime = 6,
				impulseboost = 0.123,
				impulsefactor = 0.123,
				model = "cormhmsl",
				name = "Rocket",
				noselfdamage = true,
				range = 650,
				reloadtime = 6,
				selfprop = 1,
				smoketrail = false,
				soundstart = "rocklit1",
				soundhit = "xplosml2",
				trajectoryheight = 1.0,
				turnrate = 4000,
				turret = true,
				weaponacceleration = 100,
				weapontimer = 6,
				weapontype = "MissileLauncher",
				startvelocity = 100,
				weaponvelocity = 400,
				wobble = 8700,
				damage = {
					default = 250,
					subs = 5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "CORMH_WEAPON1",
				onlytargetcategory = "NOTAIR",
				MainDir = "0 0 1",
				MaxAngleDif = 60,
			},
		},
	},
}
