return {
	mammouth = {
		acceleration = 0.022,
		brakerate = 0.025,
		buildcostenergy = 4800,
		buildcostmetal = 420,
		buildpic = "ARMSTUMP.DDS",
		buildtime = 6000,
		canmove = true,
		category = "ALL TANK MOBILE WEAPON NOTSUB NOTSHIP NOTAIR",
		corpse = "DEAD",
		collisionvolumeoffsets = "0 -15 -1",
		collisionvolumescales = "55 60 55",
		collisionvolumetest = 1,
		collisionvolumetype = "CylZ",
    customparams = {
      turretyawrate = 180,
	  turretpitchrate = 100,
    },
		description = "Heavy Machinegun Tank (Close quarters tank)",
		explodeas = "BIG_UNITEX",
		footprintx = 4,
		footprintz = 4,
		icontype = "type1",
		idleautoheal = 5,
		idletime = 1800,
		leavetracks = true,
		maxdamage = 2650,
		maxslope = 10,
		maxvelocity = 1.6,
		maxwaterdepth = 12,
		movementclass = "TANK4",
		name = "Mammoth",
		nochasecategory = "VTOL",
		objectname = "mammouth",
		seismicsignature = 0,
		selfdestructas = "BIG_UNIT",
		sightdistance = 325,
		trackoffset = 3,
		trackstrength = 6,
		tracktype = "StdTank",
		trackwidth = 24,
		turnrate = 484,
		sfxtypes = {
		explosiongenerators = {
		"custom:RAIDMUZZLE",
		"custom:STOMPSHELLS",
		},
	},
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "25.7996826172 19.2875671387 29.4318847656",
				collisionvolumeoffsets = "-0.0399932861328 0.00128356933594 -0.564636230469",
				category = "corpses",
				damage = 1056,
				description = "Mammoth Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 4,
				footprintz = 4,
				height = 20,
				hitdensity = 100,
				metal = 252,
				object = "mammouth_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 528,
				description = "Mammoth Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 4,
				footprintz = 4,
				height = 4,
				hitdensity = 100,
				metal = 111,
				object = "4X4D",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "tarmmove",
			},
			select = {
				[1] = "tarmsel",
			},
		},
		weapondefs = {
			gray_mgun1 = {
				areaofeffect = 8,
				burst = 6,
				burstrate = 0.15,
				beamtime = 0.10,
				corethickness = 0.20,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:EMG_HIT",
				edgeeffectiveness = 1,
				firestarter = 30,
				impactonly = 1,
				impulseboost = 1,
				impulsefactor = 1,
				color = 255,
				color2 = 226,
				name = "Machinegun",
				noselfdamage = true,
				projectiles = 1,
				range = 270,
				rendertype = 4,
				reloadtime = 0.7,
				soundhit = "softblat",
				soundstart = "softblam3",
				soundtrigger = true,
				sprayangle = 2000,
				targetmoveerror = 0.20000000298023,
				thickness = 0.8,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 700,
				damage = {
					bombers = 3,
					default = 17,
					fighters = 3,
					subs = 3,
					vtol = 2,
				},
			},
				gray_mgun2 = {
				areaofeffect = 8,
				burst = 6,
				burstrate = 0.15,
				beamtime = 0.10,
				corethickness = 0.15,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:EMG_HIT",
				edgeeffectiveness = 1,
				firestarter = 30,
				impactonly = 1,
				impulseboost = 1,
				impulsefactor = 1,
				color = 255,
				color2 = 226,
				name = "Machinegun",
				noselfdamage = true,
				projectiles = 1,
				range = 230,
				rendertype = 4,
				reloadtime = 0.7,
				soundhit = "softblat",
				soundstart = "softblam3",
				soundtrigger = true,
				sprayangle = 1800,
				targetmoveerror = 0.20000000298023,
				thickness = 0.5,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 700,
				damage = {
					bombers = 3,
					default = 10,
					fighters = 3,
					subs = 3,
					vtol = 2,
				},
			},
			gray_mgun3 = {
				areaofeffect = 8,
				burst = 6,
				burstrate = 0.15,
				beamtime = 0.10,
				corethickness = 0.15,
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:EMG_HIT",
				edgeeffectiveness = 1,
				firestarter = 30,
				impactonly = 1,
				impulseboost = 1,
				impulsefactor = 1,
				color = 255,
				color2 = 226,
				name = "Machinegun",
				noselfdamage = true,
				projectiles = 1,
				range = 230,
				rendertype = 4,
				reloadtime = 0.7,
				soundhit = "softblat",
				soundstart = "softblam3",
				soundtrigger = true,
				sprayangle = 1800,
				targetmoveerror = 0.20000000298023,
				thickness = 0.5,
				tolerance = 10000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 700,
				damage = {
					bombers = 3,
					default = 10,
					fighters = 3,
					subs = 3,
					vtol = 2,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "gray_mgun1",
				},
			[2] = {
				badtargetcategory = "VTOL",
				def = "gray_mgun2",
				},
			[3] = {
				badtargetcategory = "VTOL",
				def = "gray_mgun3",
			},
		},
	},
}
