return {
	scorpion = {
		acceleration = 0.023000000044703,
		brakerate = 0.10000000149012,
		buildcostenergy = 65687,
		buildcostmetal = 3120,
		buildpic = "ARMSHOCK.png",
		buildtime = 101218,
		canmove = true,
		category = "ALL NOTSTRUCTURE NOTSUB WEAPON NOTAIR",
		collisionvolumeoffsets = "0 -6 1",
		collisionvolumescales = "67 45 163",
		collisionvolumetest = 1,
		collisionvolumetype = "Ell",
		corpse = "DEAD",
		description = "All-Terrain Heavy Plasma Cannon",
		explodeas = "SHOCKER",
		footprintx = 14,
		footprintz = 14,
		hightrajectory = 2,
		idleautoheal = 150,
		idletime = 900,
		mass = 200000,
		maxdamage = 15000,
		maxslope = 17,
		maxvelocity = 1.1000000238419,
		maxwaterdepth = 0,
		movementclass = "ATANK14",
		name = "Vanguard",
		nochasecategory = "VTOL",
		objectname = "scorpion",
		seismicsignature = 0,
		selfdestructas = "SHOCKER",
		sightdistance = 625,
		smoothanim = true,
		turnrate = 131,
		featuredefs = {
			dead = {
				blocking = true,
				collisionvolumetype = "Box",
				collisionvolumescales = "64.0154266357 41.4324188232 55.433883667",
				collisionvolumeoffsets = "-3.37104034424 -1.05229058838 1.8899307251",
				category = "corpses",
				damage = 3000,
				description = "Vanguard Wreckage",
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 20,
				hitdensity = 100,
				metal = 2028,
				object = "ARMSHOCK_DEAD",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 3015,
				description = "Vanguard Heap",
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 3,
				footprintz = 3,
				height = 4,
				hitdensity = 100,
				metal = 811,
				object = "4X4D",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbarmmov",
			},
			select = {
				[1] = "kbarmsel",
			},
		},
		weapondefs = {
			lightningtail = {
				areaofeffect = 8,
				color = 128,
				color2 = 130,
				craterboost = 0,
				cratermult = 0,
				duration = 8,
				explosiongenerator = "custom:LIGHTNINGPLOSION",
				cegtag = "LASERGLOWBLAU",
				firestarter = 50,
				impactonly = 1,
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				name = "LightningGun",
				noselfdamage = true,
				range = 800,
				reloadtime = 1.1499999761581,
				rgbcolor = "0.5 0.5 1",
				soundhit = "lashit",
				soundstart = "lghthvy1",
				soundtrigger = true,
				thickness = 2,
				turret = true,
				texture1 = "lightning",
				weapontype = "LightningCannon",
				weaponvelocity = 450,
				damage = {
					bombers = 50,
					default = 200,
					fighters = 50,
					subs = 3,
					vtol = 50,
				},
			},
			sabot = {
				areaofeffect = 24,
				burnblow = true,
				cegtag = "RocketTrailxD",
				craterboost = 0,
				cratermult = 0,
				explosiongenerator = "custom:GAUSS_Expl",
				firestarter = 70,
				impulseboost = 0.12300000339746,
				impulsefactor = 0.12300000339746,
				model = "missile",
				name = "Sabot",
				noselfdamage = true,
				range = 800,
				reloadtime = 2,
				smoketrail = false,
				soundhit = "SabotHit",
				soundstart = "SabotFire",
				startvelocity = 700,
				targetmoveerror = 0.20000000298023,
				tolerance = 8000,
				tracks = true,
				turnrate = 4000,
				turret = true,
				weaponacceleration = 300,
				weapontimer = 0.10000000149012,
				weapontype = "MissileLauncher",
				weaponvelocity = 1000,
				damage = {
					bombers = 26,
					default = 500,
					fighters = 26,
					subs = 5,
					vtol = 26,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "lightningtail",
				onlytargetcategory = "NOTAIR",
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "sabot",
				onlytargetcategory = "NOTAIR",
			},
		},
	},
}
